name = "aseva-aseva-sales-deck"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_NAME = "aseva-sales-deck"
ENVIRONMENT = "production"

[[rules]]
type = "Text"
globs = ["**/*.html"]

[[d1_databases]]
binding = "DB"
database_name = "aseva-sales-deck"
database_id = "37d663f3-74b1-45bc-9c93-d38ed9e1d349"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "aseva-sales-deck"

[[kv_namespaces]]
binding = "KV"
id = "e28149934c3b40df85745646e214f3c6"

[[routes]]
pattern = "slides.aseva.ai/*"
zone_name = "aseva.com"
